name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container: node:20

    steps:
      - name: Repozitoriyi Kopyala
        uses: actions/checkout@v3

      - name: Node.js Kur
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Bağımlılıkları Yükle (CI)
        run: npm ci

      - name: Testleri Çalıştır
        run: npm test

      - name: Çalıştır
        run: npm start